version: "3.9"  # optional since v1.27.0
services:
  mdns-reflector:
    container_name: mDNS-reflector
    image: flungo/avahi
    restart: unless-stopped
    networks:
      - mDNS
    environment:
      - REFLECTOR_ENABLE_REFLECTOR=yes
networks:
  mDNS: